### ISSUE TITLE
`click-extra` after upgrading to 1.7.0

### ISSUE THREAD

**Issue by pdelre** [kdeldycke/meta-package-manager#518]
Seems that this project uses `click-extra.run.run`, which was removed in [`click-extra` `1.7.0`](https://github.com/kdeldycke/click-extra/blob/main/changelog.md#170-2022-03-31).

```shell
$ mpm --help
Traceback (most recent call last):
  File "/usr/local/bin/mpm", line 5, in <module>
    from meta_package_manager.cli import mpm
  File "/Users/pdelre/Library/Python/3.9/lib/python/site-packages/meta_package_manager/cli.py", line 49, in <module>
    from .base import CLI_FORMATS, CLIError, PackageManager
  File "/Users/pdelre/Library/Python/3.9/lib/python/site-packages/meta_package_manager/base.py", line 31, in <module>
    from click_extra.run import INDENT, PROMPT, run
ImportError: cannot import name 'run' from 'click_extra.run' (/Users/pdelre/Library/Python/3.9/lib/python/site-packages/click_extra/run.py)
```

**Comment by kdeldycke** [comment]
Just released `mpm v4.10.0`. Should be available on PyPi in a couple of minutes, after the GitHub actions workflow finishes their jobs.

**Comment by pdelre** [comment]
Thank you for resolving so quickly!

**Comment by pdelre** [comment]
I'm now experiencing the Issue in a loop, which could be a project Issue or could be a user issue. I'm not experienced with Python/pip/etc to determine which.

Here is the usage scenario (MacOS, python installed via `brew`):

```
# I update mpm
$ pip3 install --force meta-package-manager
...
Successfully installed boltons-21.0.0 certifi-2021.10.8 charset-normalizer-2.0.12 cli-helpers-2.2.1 click-8.1.2 click-extra-1.6.4 click-log-0.3.2 cloup-0.13.0 configobj-5.0.6 idna-3.3 meta-package-manager-4.10.0 pyyaml-6.0 requests-2.27.1 six-1.16.0 tabulate-0.8.9 tomli-2.0.1 tomli_w-1.0.0 urllib3-1.26.9 wcwidth-0.2.5

# I run `mpm outdated`, which shows `click-extra`
$ mpm outdated
╭──────────────┬─────────────┬─────────┬───────────────────┬────────────────╮
│ Package name │ ID          │ Manager │ Installed version │ Latest version │
├──────────────┼─────────────┼─────────┼───────────────────┼────────────────┤
│ click-extra  │ click-extra │ pip     │ 1.6.4             │ 1.7.0          │
│ click-log    │ click-log   │ pip     │ 0.3.2             │ 0.4.0          │
╰──────────────┴─────────────┴─────────┴───────────────────┴────────────────╯
2 packages total (pip: 2).

# I run `mpm upgrade`, which updates `click-extra` to 1.7.0 & breaks mpm
$ mpm upgrade
Requirement already satisfied: click-extra in /usr/local/lib/python3.9/site-packages (1.6.4)
Collecting click-extra
  Using cached click_extra-1.7.0-py3-none-any.whl (41 kB)
...
Installing collected packages: click-extra
Successfully installed click-extra-1.7.0
...

# I run `mpm outdated` and back into the failure
$ mpm outdated
Traceback (most recent call last):
  File "/usr/local/bin/mpm", line 5, in <module>
    from meta_package_manager.cli import mpm
  File "/usr/local/lib/python3.9/site-packages/meta_package_manager/cli.py", line 54, in <module>
    from .base import CLI_FORMATS, CLIError, PackageManager
  File "/usr/local/lib/python3.9/site-packages/meta_package_manager/base.py", line 31, in <module>
    from click_extra.run import INDENT, PROMPT, run
ImportError: cannot import name 'run' from 'click_extra.run' (/Users/pdelre/Library/Python/3.9/lib/python/site-packages/click_extra/run.py)
```

Am I using mpm incorrectly or could I have an improperly setup python environment (not using virtualenvs for global tooling)?

**Comment by kdeldycke** [comment]
Your issue stems from the fact that `mpm` (the package) has been installed in your global Python environment and can't possibly impose a lower requirement on `click_extra` to cap its version to `<1.7.0`. Global `pip` will not enforce that requirement.

So when the global `mpm` (the CLI) is calling the global `pip`, the latter is reporting a new `click_extra` version available for upgrade. And that breaks `mpm`.

Thanks for pointing out this issue. It's kind of meta and I wasn't careful enough managing the dependencies. I'll fix it up and make a new release.

**Comment by kdeldycke** [comment]
I just released `click-extra v1.8.0` and `meta-package-manager v4.11.0`. Should fix your issue.

**Comment by pdelre** [comment]
Thank you! I've updated everything and it seems to avoid the dependency conflict loop.
