### ISSUE TITLE
Not working with python 3.10.1

### ISSUE THREAD

**Issue by reegnz** [kdeldycke/meta-package-manager#467]
After installing I get this error message:

```sh
❯ mpm
Traceback (most recent call last):
  File "/Users/zoltanreegn/.local/bin/mpm", line 5, in <module>
    from meta_package_manager.cli import mpm
  File "/Users/zoltanreegn/.local/pipx/venvs/meta-package-manager/lib/python3.10/site-packages/meta_package_manager/cli.py", line 32, in <module>
    from click_extra.colorize import KO, OK, theme
  File "/Users/zoltanreegn/.local/pipx/venvs/meta-package-manager/lib/python3.10/site-packages/click_extra/colorize.py", line 25, in <module>
    from boltons.ecoutils import get_profile
  File "/Users/zoltanreegn/.local/pipx/venvs/meta-package-manager/lib/python3.10/site-packages/boltons/ecoutils.py", line 357, in <module>
    _real_safe_repr = pprint._safe_repr
AttributeError: module 'pprint' has no attribute '_safe_repr'. Did you mean: 'saferepr'?
```

Works fine with 3.9 and 3.8 though.

**Comment by kdeldycke** [comment]
Oh yes you're right. This is an issue with `boltons` dependency. See: https://github.com/mahmoud/boltons/issues/294

I'm waiting for a new release of `boltons` so this will be fixed naturally.

For reference, this issue is mentioned in commits:
* https://github.com/kdeldycke/meta-package-manager/commit/f6102da9123d9602396e74eb257d0e48b810a397
* https://github.com/kdeldycke/meta-package-manager/commit/380974b79bcbcaa6464bcad2ba0afb79fc974b59
* https://github.com/kdeldycke/meta-package-manager/commit/4b28e5fdbff3ec8320c4092456c55f5e9c336f61

**Comment by kdeldycke** [comment]
I just released meta-package-manager v4.9.10, which includes the fix for Python 3.10.
